# Generated by Django 5.2.5 on 2025-08-29 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="publication_year",
        ),
        migrations.AddField(
            model_name="book",
            name="published_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
