# Generated by Django 5.2.5 on 2025-08-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0002_remove_book_publication_year_book_published_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="published_date",
        ),
        migrations.AddField(
            model_name="book",
            name="publication_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
